name: deploy lambda
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: set up python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11
            - name: install libraries
              run: |
                cd function
                python -m pip install --upgrade pip
                if [ -f requirments.txt ]; then pip install -r requirments.txt -t .; fi
            - name: create a zip bundle
              run: |
                cd function
                zip -r ../${{ github.sha }}.zip .

            - name: Archive artifact
              uses: actions/upload-artifact@v2
              with:
                name: zipped-bundle
                path: ${{ github.sha }}.zip